# -*- coding: utf-8 -*-
"""CovidWorld.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OjQeZzBNKkrB20VjAuCBkxmOZn1Cr7Q9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel("/content/drive/My Drive/Covid/owid-covid-data.xlsx",sheet_name=None)
ar = df['Sheet1'].to_numpy()
country = np.unique(ar.T[1],True)
print(country[1])

indi = country[1].copy()
indi.sort()
print(indi)

case = {}
for i in range(len(indi)-1):
  a = ar.T[4][indi[i]:indi[i+1]]
  case[country[0][np.where(country[1] == indi[i])[0][0]]] = a.clip(min=0)
a = ar.T[4][indi[i+1]:]
case[country[0][np.where(country[1] == indi[i+1])[0][0]]] = a.clip(min=0)
print(case)

print(case["Ecuador"])

import scipy
from scipy import signal
plt.figure(figsize=(60,500))#figsize=(60,500)
order = 5
sampling_freq = 100
cutoff_freq = 10
normalized_cutoff_freq = 2 * cutoff_freq / sampling_freq
numerator_coeffs, denominator_coeffs = scipy.signal.butter(order, normalized_cutoff_freq)
for i in range(len(case)):#len(case)
  a = case[country[0][i]]
  filtered_signal = scipy.signal.lfilter(numerator_coeffs, denominator_coeffs, a).clip(min=0)
  plt.subplot(53,4,i+1)
  #plt.subplot(4,1,i+1)
  plt.plot(range(len(a)),a)
  plt.plot(range(len(a)),filtered_signal)
  plt.title(country[0][i])
  
plt.show()

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt


window_size = 20
batch_size = 32
shuffle_buffer_size = 1000


split_time = int(len(series)*0.7)
time_train = time[:split_time]
x_train = series[:split_time]
time_valid = time[split_time:]
x_valid = series[split_time:]

"""# **###Extras###**"""

from scipy import fftpack
f_s = 100
for i in range(10):
  X = fftpack.fft(case[country[0][i]])
  freqs = fftpack.fftfreq(len(case[country[0][i]])) * f_s
  fig, ax = plt.subplots()

  ax.stem(freqs, np.abs(X))
  ax.set_xlabel('Frequency in Hertz [Hz]')
  ax.set_ylabel('Frequency Domain (Spectrum) Magnitude')